### ISSUE TITLE
Can we use own voice Or any other sample?

### ISSUE THREAD

**Issue by Sachinart** [synesthesiam/docker-mozillatts#1]
Hello, We can easily create text to speech using JS or PHP under 15-20kb program. My question is what this tool allows us to clone voice (will provide clear audio file) using text? If yes then please share about it how?

Thank You!

**Comment by synesthesiam** [comment]
I haven't tried training with this Docker image yet. I'd recommend @erogol's [CoLab notebook](https://gist.github.com/erogol/97516ad65b44dbddb8cd694953187c5b) for that.
