### ISSUE TITLE
failed to get the WAV audio

### ISSUE THREAD

**Issue by yqu212** [synesthesiam/docker-mozillatts#11]
I run docker from a Synology DS918+, whose cpu is a Celeron.

> docker run -it -p 5002:5002 synesthesiam/mozillatts:en-noavx

I can visit the web interface. Howerer, when I hit Speak, I get the following message.

> [INFO]  * Running on http://0.0.0.0:5002/ (Press CTRL+C to quit)
> [INFO] Synthesizing (16 char(s))...
> [INFO] initializing backend espeak-1.48.03
> /run.sh: line 3:     6 Illegal instruction     (core dumped) bin/python3 -m tts_web "$@"

I have tried synesthesiam/mozillatts. I got the same result.

I just want to convert some text to audio with TTS.

Can anyone help me?

**Comment by pipip** [comment]
I have the same problem with synesthesiam/mozillatts:

>[INFO] Synthesizing (24 char(s))...
[INFO] initializing backend espeak-1.48.03
/run.sh: line 3:     8 Illegal instruction     (core dumped) bin/python3 -m tts_web "$@"

**Comment by synesthesiam** [comment]
See https://github.com/synesthesiam/docker-mozillatts/issues/17
