### ISSUE TITLE
Limited to 34 seconds

### ISSUE THREAD

**Issue by Eimuex** [synesthesiam/docker-mozillatts#3]
Hello, no matter how long the text is, it limits recorded session to 34 seconds. Is it possible to increase this? 
Thank you.

**Comment by synesthesiam** [comment]
This seems to be baked into the model as `max_decoder_steps` in the decoder layer. From the commit I used for MozillaTTS (b1935c97), this is set to 1000 for Tacotron2 models. I don't believe it can be changed without re-training the model.

I think you'll have to split your text into multiple requests, probably best by sentences.

**Comment by Eimuex** [comment]
Thank you for response! It seems like a lot of work to convert a book for example. Shame, thanks anyway.

**Comment by synesthesiam** [comment]
It could be automated pretty easily in Python, using something like NLTK or spaCy. Just split the text into sentences, POST each sentence to `/api/tts`, and save the WAV audio with a timestamp. When it's done, you can join the audio with something like:

```sh
$ ffmpeg -f concat -i list_of_wav_files.txt -c copy output.wav
```

**Comment by Eimuex** [comment]
I'm not a programmer, but will give it a try. Thanks a lot!
