### ISSUE TITLE
French model

### ISSUE THREAD

**Issue by msharp1** [synesthesiam/docker-mozillatts#4]
I tested the docker image, it works well, thanks !. Do you have specific instructions to rebuild the image with a French model ?

**Comment by synesthesiam** [comment]
If you're looking for something pre-packaged, I have a Docker image available with a French model: https://github.com/rhasspy/fr_larynx-siwis

```sh
$ docker run -it -p 5002:5002 \
    --device /dev/snd:/dev/snd \
    rhasspy/larynx:fr-siwis-1
```

This should be a drop-in replacement for the MozillaTTS Docker image :smile: 

If you happen to use Home Assistant, I also have a Hass.io addon available: https://github.com/rhasspy/hassio-addons
