### ISSUE TITLE
Docker Does not start 

### ISSUE THREAD

**Issue by LeducH** [synesthesiam/docker-mozillatts#5]
I want to start the  mozialla TTS with docker 

As described I tried 
```
 docker run -it -p 5002:5002 synesthesiam/mozilla-tts
```
without success 

I get the error 

```
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by synesthesiam** [comment]
This image will only work on `x86_64` CPUs right now. I'm guessing you tried to start it on an ARM device?

**Comment by synesthesiam** [comment]
I updated the image yesterday to include support for ARM :+1:
