### ISSUE TITLE
Question: GPU based

### ISSUE THREAD

**Issue by OkenKhuman** [synesthesiam/docker-mozillatts#6]
Is this image capable of using GPU?

**Comment by synesthesiam** [comment]
I don't think so, unfortunately. There's not CUDA installed in the image, so it wouldn't find the libraries. Basing the image off one of the [official CUDA images](https://hub.docker.com/r/nvidia/cuda) could solve this problem.

**Comment by OkenKhuman** [comment]
Thanks for reply. 

I will just fall back to your maryTTS image as it is more light.
