### ISSUE TITLE
Server closes connection before finished with text.

### ISSUE THREAD

**Issue by Aaaamu** [synesthesiam/docker-mozillatts#7]
Hi there,
When I feed the tts with more then a line or two of text it closes the connection. 
I use `t="text="`cat 56.txt`;curl -v -G --output  -     --data-urlencode "$t"     'http://localhost:5002/api/tts' |  cat>test.wav
`
where 56.txt is a file with 56 lines (3204 characters) of english language text.

thinking, that the problem could be some limitation of the length of an url, I tried:
`t=`cat 56.txt`;curl -X POST --output  -     --data "$t"     'http://localhost:5002/api/tts' |  cat>test.wav
`
but here, I just get an empty file and the folowing response in the terminal:
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3522  100   290  100  3232   1835  20455 --:--:-- --:--:-- --:--:-- 22291`

My goal would be to feed it with much longer texts. I guess GET must fail there, but I can not figure out why POST should not work, the way I tried it. (it fails too, if i feed it with `'This is a test-text. Yay'` instead of `"$t"`
Do you think the POST method of the docker image is failing, or is my line of code faulty?
```
curl -V
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
```

REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
synesthesiam/mozillatts      latest              ae5bf234ed9b        26 hours ago        1.83GB
```

**Comment by synesthesiam** [comment]
The POST apparently needs `-H "Content-Type: text/plain"` from `curl`. The flask web server gives me an empty data string without it for some reason.

I also recently added a feature to independently synthesize lines. So if you break your sentences into lines, you can feed the whole thing now without overwhelming the synthesizer. It'll do each line in turn, and then combine all the audio before responding :smile:
